---
title: Jak obsłużyć wyjątek przy użyciu przewodnika try C# -catch-programowanie
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: adfc53cbe4fd603ac3a6de6b9a0162320d5a2e19
ms.sourcegitcommit: 5f236cd78cf09593c8945a7d753e0850e96a0b80
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 01/07/2020
ms.locfileid: "75712289"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="36660-102">Jak obsłużyć wyjątek za pomocą try/catchC# (Przewodnik programowania)</span><span class="sxs-lookup"><span data-stu-id="36660-102">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="36660-103">Celem bloku [try-catch](../../language-reference/keywords/try-catch.md) jest przechwycenie i obsłużenie wyjątku wygenerowanego przez kod roboczy.</span><span class="sxs-lookup"><span data-stu-id="36660-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="36660-104">Niektóre wyjątki mogą być obsługiwane w bloku `catch` i problem rozwiązany bez ponownego zgłaszania wyjątku; Jednak w większości przypadków Jedyną czynnością, którą można wykonać, jest upewnienie się, że jest zgłaszany odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="36660-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="36660-105">Przykład</span><span class="sxs-lookup"><span data-stu-id="36660-105">Example</span></span>  
 <span data-ttu-id="36660-106">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest najbardziej odpowiedni wyjątek: <xref:System.ArgumentOutOfRangeException> ma sens dla metody, ponieważ błąd jest spowodowany przez argument `index` przekazaną przez wywołującego.</span><span class="sxs-lookup"><span data-stu-id="36660-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="36660-107">Komentarze</span><span class="sxs-lookup"><span data-stu-id="36660-107">Comments</span></span>  
 <span data-ttu-id="36660-108">Kod, który powoduje wyjątek, jest ujęty w bloku `try`.</span><span class="sxs-lookup"><span data-stu-id="36660-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="36660-109">Instrukcja `catch` jest dodawana natychmiast po `IndexOutOfRangeException`do obsługi, jeśli wystąpi.</span><span class="sxs-lookup"><span data-stu-id="36660-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="36660-110">Blok `catch` obsługuje `IndexOutOfRangeException` i zgłasza zamiast tego bardziej odpowiedni wyjątek `ArgumentOutOfRangeException`.</span><span class="sxs-lookup"><span data-stu-id="36660-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="36660-111">Aby zapewnić wywołującemu możliwie jak najwięcej informacji, rozważ określenie oryginalnego wyjątku jako <xref:System.Exception.InnerException%2A> nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="36660-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="36660-112">Ponieważ właściwość <xref:System.Exception.InnerException%2A> jest [tylko do odczytu](../../language-reference/keywords/readonly.md), należy przypisać ją w konstruktorze nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="36660-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="36660-113">Zobacz także</span><span class="sxs-lookup"><span data-stu-id="36660-113">See also</span></span>

- [<span data-ttu-id="36660-114">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="36660-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="36660-115">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="36660-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="36660-116">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="36660-116">Exception Handling</span></span>](./exception-handling.md)
