---
title: Jak obsługiwać wyjątek za pomocą try-catch - C# Programming Guide
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: adfc53cbe4fd603ac3a6de6b9a0162320d5a2e19
ms.sourcegitcommit: 7588136e355e10cbc2582f389c90c127363c02a5
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 03/14/2020
ms.locfileid: "75712289"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="8870d-102">Jak obsługiwać wyjątek przy użyciu try/catch (Przewodnik programowania C#)</span><span class="sxs-lookup"><span data-stu-id="8870d-102">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="8870d-103">Celem bloku [try-catch](../../language-reference/keywords/try-catch.md) jest catch i obsługi wyjątku generowanego przez kod roboczy.</span><span class="sxs-lookup"><span data-stu-id="8870d-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="8870d-104">Niektóre wyjątki mogą być `catch` obsługiwane w bloku i problem rozwiązany bez ponownego wystąpienia wyjątku; jednak częściej jedyną rzeczą, którą możesz zrobić, to upewnić się, że zostanie zgłoszony odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="8870d-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="8870d-105">Przykład</span><span class="sxs-lookup"><span data-stu-id="8870d-105">Example</span></span>  
 <span data-ttu-id="8870d-106">W tym <xref:System.IndexOutOfRangeException> przykładzie nie jest najbardziej <xref:System.ArgumentOutOfRangeException> odpowiedni wyjątek: ma większy sens dla `index` metody, ponieważ błąd jest spowodowany przez argument przekazany przez obiekt wywołujący.</span><span class="sxs-lookup"><span data-stu-id="8870d-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="8870d-107">Komentarze</span><span class="sxs-lookup"><span data-stu-id="8870d-107">Comments</span></span>  
 <span data-ttu-id="8870d-108">Kod, który powoduje wyjątek jest `try` ujęty w bloku.</span><span class="sxs-lookup"><span data-stu-id="8870d-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="8870d-109">Instrukcja `catch` jest dodawana natychmiast po obsłudze `IndexOutOfRangeException`, jeśli występuje.</span><span class="sxs-lookup"><span data-stu-id="8870d-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="8870d-110">Blok `catch` obsługuje `IndexOutOfRangeException` i zgłasza bardziej odpowiedni `ArgumentOutOfRangeException` wyjątek zamiast tego.</span><span class="sxs-lookup"><span data-stu-id="8870d-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="8870d-111">Aby zapewnić obiekt wywołujący z jak najwięcej informacji, jak to <xref:System.Exception.InnerException%2A> możliwe, należy rozważyć określenie oryginalnego wyjątku jako nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="8870d-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="8870d-112">Ponieważ <xref:System.Exception.InnerException%2A> właściwość jest [tylko do odczytu](../../language-reference/keywords/readonly.md), należy przypisać go w konstruktorze nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="8870d-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="8870d-113">Zobacz też</span><span class="sxs-lookup"><span data-stu-id="8870d-113">See also</span></span>

- [<span data-ttu-id="8870d-114">Przewodnik programowania języka C#</span><span class="sxs-lookup"><span data-stu-id="8870d-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="8870d-115">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="8870d-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="8870d-116">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="8870d-116">Exception Handling</span></span>](./exception-handling.md)
