---
title: Jak obsłużyć wyjątek przy użyciu przewodnika programowania try-catch-C#
description: Dowiedz się, jak obsłużyć wyjątek przy użyciu bloku try-catch. Zobacz przykładowy kod i Wyświetl dodatkowe dostępne zasoby.
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 357aebe042bc5b6e761b3c1bad258021441de22c
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 07/28/2020
ms.locfileid: "87301999"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="ee935-104">Jak obsłużyć wyjątek przy użyciu try/catch (Przewodnik programowania w języku C#)</span><span class="sxs-lookup"><span data-stu-id="ee935-104">How to handle an exception using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="ee935-105">Celem bloku [try-catch](../../language-reference/keywords/try-catch.md) jest przechwycenie i obsłużenie wyjątku wygenerowanego przez kod roboczy.</span><span class="sxs-lookup"><span data-stu-id="ee935-105">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="ee935-106">Niektóre wyjątki mogą być obsługiwane w `catch` bloku i problem został rozwiązany bez ponownego zgłaszania wyjątku; jednak częściej, którą można wykonać, jest upewnienie się, że jest zgłaszany odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="ee935-106">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="ee935-107">Przykład</span><span class="sxs-lookup"><span data-stu-id="ee935-107">Example</span></span>  
 <span data-ttu-id="ee935-108">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest to najbardziej odpowiedni wyjątek: jest to <xref:System.ArgumentOutOfRangeException> bardziej zrozumiałe dla metody, ponieważ błąd jest spowodowany przez argument, który został `index` przesłany przez obiekt wywołujący.</span><span class="sxs-lookup"><span data-stu-id="ee935-108">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="ee935-109">Komentarze</span><span class="sxs-lookup"><span data-stu-id="ee935-109">Comments</span></span>  
 <span data-ttu-id="ee935-110">Kod, który powoduje, że wyjątek jest ujęty w `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="ee935-110">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="ee935-111">`catch`Instrukcja jest dodawana natychmiast po do dojścia `IndexOutOfRangeException` , jeśli wystąpi.</span><span class="sxs-lookup"><span data-stu-id="ee935-111">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="ee935-112">`catch`Blok obsługuje `IndexOutOfRangeException` i zgłasza `ArgumentOutOfRangeException` zamiast niego bardziej odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="ee935-112">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="ee935-113">Aby zapewnić wywołującemu możliwie jak najwięcej informacji, rozważ określenie oryginalnego wyjątku jako <xref:System.Exception.InnerException%2A> nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="ee935-113">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="ee935-114">Ponieważ <xref:System.Exception.InnerException%2A> Właściwość jest [tylko do odczytu](../../properties.md#read-only), należy przypisać ją w konstruktorze nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="ee935-114">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="ee935-115">Zobacz też</span><span class="sxs-lookup"><span data-stu-id="ee935-115">See also</span></span>

- [<span data-ttu-id="ee935-116">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="ee935-116">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="ee935-117">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="ee935-117">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="ee935-118">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="ee935-118">Exception Handling</span></span>](./exception-handling.md)
