---
title: 'Instrukcje: Obsługa wyjątków za pomocą bloku try-catch - C# Programming Guide'
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 0524248a0b82ddc115e82108f774e894f1dc2f26
ms.sourcegitcommit: 41c0637e894fbcd0713d46d6ef1866f08dc321a2
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 03/01/2019
ms.locfileid: "57201615"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="5fb40-102">Instrukcje: Obsługa wyjątków za pomocą bloku try/catch (C# Programming Guide)</span><span class="sxs-lookup"><span data-stu-id="5fb40-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="5fb40-103">Celem [try-catch —](../../../csharp/language-reference/keywords/try-catch.md) blok jest zdołały wychwycić i obsłużyć wyjątek, generowane przez działającego kodu.</span><span class="sxs-lookup"><span data-stu-id="5fb40-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="5fb40-104">Niektóre wyjątki mogą być obsługiwane w `catch` bloku i problem rozwiązany bez wyjątku jest zgłoszony ponownie; jednak częściej jedyną czynnością, które można wykonać jest upewnij się, że zgłoszony odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="5fb40-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="5fb40-105">Przykład</span><span class="sxs-lookup"><span data-stu-id="5fb40-105">Example</span></span>  
 <span data-ttu-id="5fb40-106">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest najbardziej odpowiedni wyjątek: <xref:System.ArgumentOutOfRangeException> zapewnia bardziej zrozumiałe dla metody, ponieważ błąd jest spowodowany przez `index` argumentu przekazanego przez obiekt wywołujący.</span><span class="sxs-lookup"><span data-stu-id="5fb40-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="5fb40-107">Komentarze</span><span class="sxs-lookup"><span data-stu-id="5fb40-107">Comments</span></span>  
 <span data-ttu-id="5fb40-108">Kod, który powoduje wyjątek jest ujęty w `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="5fb40-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="5fb40-109">A `catch` instrukcja dodaje się natychmiast po do obsługi `IndexOutOfRangeException`, jeśli występuje.</span><span class="sxs-lookup"><span data-stu-id="5fb40-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="5fb40-110">`catch` Block uchwyty `IndexOutOfRangeException` i zgłasza bardziej odpowiednie `ArgumentOutOfRangeException` wyjątku zamiast tego.</span><span class="sxs-lookup"><span data-stu-id="5fb40-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="5fb40-111">Aby można było podać obiekt wywołujący jak najwięcej informacji, jak to możliwe, należy wziąć pod uwagę oryginalnego wyjątku, ponieważ określenie <xref:System.Exception.InnerException%2A> nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="5fb40-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="5fb40-112">Ponieważ <xref:System.Exception.InnerException%2A> właściwość [tylko do odczytu](../../../csharp/language-reference/keywords/readonly.md), należy je przypisać w Konstruktorze nowy wyjątek.</span><span class="sxs-lookup"><span data-stu-id="5fb40-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="5fb40-113">Zobacz także</span><span class="sxs-lookup"><span data-stu-id="5fb40-113">See also</span></span>

- [<span data-ttu-id="5fb40-114">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="5fb40-114">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)
- [<span data-ttu-id="5fb40-115">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="5fb40-115">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)
- [<span data-ttu-id="5fb40-116">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="5fb40-116">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)
