---
title: Jak obsłużyć wyjątek przy użyciu przewodnika programowania try-catch-C#
description: Dowiedz się, jak obsłużyć wyjątek przy użyciu bloku try-catch. Zobacz przykładowy kod i Wyświetl dodatkowe dostępne zasoby.
ms.date: 12/09/2020
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: b6368660dbe037123f5bb6ce52502d4a94fcfc3a
ms.sourcegitcommit: 9b877e160c326577e8aa5ead22a937110d80fa44
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 12/11/2020
ms.locfileid: "97110523"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="7b6e8-104">Jak obsłużyć wyjątek przy użyciu try/catch (Przewodnik programowania w języku C#)</span><span class="sxs-lookup"><span data-stu-id="7b6e8-104">How to handle an exception using try/catch (C# Programming Guide)</span></span>

<span data-ttu-id="7b6e8-105">Celem bloku [try-catch](../../language-reference/keywords/try-catch.md) jest przechwycenie i obsłużenie wyjątku wygenerowanego przez kod roboczy.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-105">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="7b6e8-106">Niektóre wyjątki mogą być obsługiwane w `catch` bloku i problem został rozwiązany bez zgłaszania wyjątku, jednak częściej, którą można wykonać, jest upewnienie się, że jest zgłaszany odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-106">Some exceptions can be handled in a `catch` block and the problem solved without the exception being rethrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>

## <a name="example"></a><span data-ttu-id="7b6e8-107">Przykład</span><span class="sxs-lookup"><span data-stu-id="7b6e8-107">Example</span></span>

<span data-ttu-id="7b6e8-108">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest to najbardziej odpowiedni wyjątek: jest to <xref:System.ArgumentOutOfRangeException> bardziej zrozumiałe dla metody, ponieważ błąd jest spowodowany przez argument, który `index` przeszedł przez wywołującego.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-108">In this example, <xref:System.IndexOutOfRangeException> isn't the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>

:::code language="csharp" source="snippets/exceptions/ExampleTryCatch.cs" id="ExampleTryCatch":::

## <a name="comments"></a><span data-ttu-id="7b6e8-109">Komentarze</span><span class="sxs-lookup"><span data-stu-id="7b6e8-109">Comments</span></span>

<span data-ttu-id="7b6e8-110">Kod, który powoduje, że wyjątek jest ujęty w `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-110">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="7b6e8-111">`catch`Instrukcja jest dodawana natychmiast po do dojścia `IndexOutOfRangeException` , jeśli wystąpi.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-111">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="7b6e8-112">`catch`Blok obsługuje `IndexOutOfRangeException` i zgłasza `ArgumentOutOfRangeException` zamiast niego bardziej odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-112">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="7b6e8-113">Aby zapewnić wywołującemu możliwie jak najwięcej informacji, rozważ określenie oryginalnego wyjątku jako <xref:System.Exception.InnerException%2A> nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-113">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="7b6e8-114">Ponieważ <xref:System.Exception.InnerException%2A> Właściwość jest [tylko do odczytu](../../properties.md#read-only), należy przypisać ją w konstruktorze nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="7b6e8-114">Because the <xref:System.Exception.InnerException%2A> property is [read-only](../../properties.md#read-only), you must assign it in the constructor of the new exception.</span></span>
