---
title: 'Instrukcje: Obsługa wyjątku przy użyciu przewodnika try- C# catch-programowanie'
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 5378de09962055fe7d2e100484ad69662c803e0f
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 08/19/2019
ms.locfileid: "69590237"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="b152c-102">Instrukcje: Obsługuj wyjątek za pomocą try/catch (C# Przewodnik programowania)</span><span class="sxs-lookup"><span data-stu-id="b152c-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="b152c-103">Celem bloku [try-catch](../../language-reference/keywords/try-catch.md) jest przechwycenie i obsłużenie wyjątku wygenerowanego przez kod roboczy.</span><span class="sxs-lookup"><span data-stu-id="b152c-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="b152c-104">Niektóre wyjątki mogą być obsługiwane w `catch` bloku i problem został rozwiązany bez ponownego zgłaszania wyjątku; jednak częściej, którą można wykonać, jest upewnienie się, że jest zgłaszany odpowiedni wyjątek.</span><span class="sxs-lookup"><span data-stu-id="b152c-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="b152c-105">Przykład</span><span class="sxs-lookup"><span data-stu-id="b152c-105">Example</span></span>  
 <span data-ttu-id="b152c-106">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest to najbardziej odpowiedni wyjątek: <xref:System.ArgumentOutOfRangeException> jest to bardziej zrozumiałe dla metody, ponieważ błąd jest spowodowany przez `index` argument, który został przesłany przez obiekt wywołujący.</span><span class="sxs-lookup"><span data-stu-id="b152c-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="b152c-107">Komentarze</span><span class="sxs-lookup"><span data-stu-id="b152c-107">Comments</span></span>  
 <span data-ttu-id="b152c-108">Kod, który powoduje, że wyjątek jest ujęty `try` w bloku.</span><span class="sxs-lookup"><span data-stu-id="b152c-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="b152c-109">Instrukcja jest dodawana natychmiast po do dojścia `IndexOutOfRangeException`, jeśli wystąpi. `catch`</span><span class="sxs-lookup"><span data-stu-id="b152c-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="b152c-110">Blok obsługuje i zgłasza zamiast niego bardziej odpowiedni `ArgumentOutOfRangeException` wyjątek. `IndexOutOfRangeException` `catch`</span><span class="sxs-lookup"><span data-stu-id="b152c-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="b152c-111">Aby zapewnić wywołującemu możliwie jak najwięcej informacji, rozważ określenie oryginalnego wyjątku jako <xref:System.Exception.InnerException%2A> nowego wyjątku.</span><span class="sxs-lookup"><span data-stu-id="b152c-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="b152c-112">Ponieważ właściwość jest tylko do odczytu, należy przypisać ją w konstruktorze nowego wyjątku. [](../../language-reference/keywords/readonly.md) <xref:System.Exception.InnerException%2A></span><span class="sxs-lookup"><span data-stu-id="b152c-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="b152c-113">Zobacz także</span><span class="sxs-lookup"><span data-stu-id="b152c-113">See also</span></span>

- [<span data-ttu-id="b152c-114">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="b152c-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="b152c-115">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="b152c-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="b152c-116">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="b152c-116">Exception Handling</span></span>](./exception-handling.md)
