---
title: "Porady: obsługa wyjątków za pomocą bloku try-catch (C# przewodnik programowania w języku)"
ms.date: 07/20/2015
ms.prod: .net
ms.technology: devlang-csharp
ms.topic: article
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
caps.latest.revision: "14"
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 9098bbcf5cefb85211f9d3bb9cac15943ba02172
ms.sourcegitcommit: 4f3fef493080a43e70e951223894768d36ce430a
ms.translationtype: MT
ms.contentlocale: pl-PL
ms.lasthandoff: 11/21/2017
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="3b468-102">Porady: obsługa wyjątków za pomocą bloku try/catch (Przewodnik programowania w języku C#)</span><span class="sxs-lookup"><span data-stu-id="3b468-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="3b468-103">Celem [try-catch](../../../csharp/language-reference/keywords/try-catch.md) blok jest zdołały wychwycić i obsłużyć wyjątek, generowane przez kod pracy.</span><span class="sxs-lookup"><span data-stu-id="3b468-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="3b468-104">Niektóre wyjątki mogą być obsługiwane w `catch` blok i ten problem można rozwiązać bez wyjątek zostanie zgłoszony ponownie, jednak częściej jedyną operacją, które można wykonać upewnij się, że odpowiednie wyjątku.</span><span class="sxs-lookup"><span data-stu-id="3b468-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="3b468-105">Przykład</span><span class="sxs-lookup"><span data-stu-id="3b468-105">Example</span></span>  
 <span data-ttu-id="3b468-106">W tym przykładzie <xref:System.IndexOutOfRangeException> nie jest najbardziej odpowiednia wyjątek: <xref:System.ArgumentOutOfRangeException> przesyła bardziej zrozumiałe dla metody, ponieważ błąd jest spowodowany przez `index` argument przekazany przez wywołującego.</span><span class="sxs-lookup"><span data-stu-id="3b468-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]  
  
## <a name="comments"></a><span data-ttu-id="3b468-107">Komentarze</span><span class="sxs-lookup"><span data-stu-id="3b468-107">Comments</span></span>  
 <span data-ttu-id="3b468-108">Kod, który powoduje zgłoszenie wyjątku jest ujęta w `try` bloku.</span><span class="sxs-lookup"><span data-stu-id="3b468-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="3b468-109">A `catch` instrukcji dodawany jest od razu po do obsługi `IndexOutOfRangeException`, jeśli występuje.</span><span class="sxs-lookup"><span data-stu-id="3b468-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="3b468-110">`catch` Zablokować uchwytów `IndexOutOfRangeException` i zgłasza wyjątek, bardziej odpowiednie `ArgumentOutOfRangeException` wyjątek zamiast tego.</span><span class="sxs-lookup"><span data-stu-id="3b468-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="3b468-111">Aby zapewnić wywołującego tylu informacji jak to możliwe, należy rozważyć określenie pierwotny wyjątek jako <xref:System.Exception.InnerException%2A> nowe wyjątku.</span><span class="sxs-lookup"><span data-stu-id="3b468-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="3b468-112">Ponieważ <xref:System.Exception.InnerException%2A> właściwość jest [tylko do odczytu](../../../csharp/language-reference/keywords/readonly.md), należy go przypisać w Konstruktorze nowego wyjątek.</span><span class="sxs-lookup"><span data-stu-id="3b468-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="3b468-113">Zobacz też</span><span class="sxs-lookup"><span data-stu-id="3b468-113">See Also</span></span>  
 [<span data-ttu-id="3b468-114">Przewodnik programowania w języku C#</span><span class="sxs-lookup"><span data-stu-id="3b468-114">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)  
 [<span data-ttu-id="3b468-115">Wyjątki i obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="3b468-115">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)  
 [<span data-ttu-id="3b468-116">Obsługa wyjątków</span><span class="sxs-lookup"><span data-stu-id="3b468-116">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)
